runtime: custom
env: flex
entrypoint: streamlit run Home.py --server.port="8501" --server.enableCORS=false --server.enableXsrfProtection=false
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"
